#!/bin/sh
# Regenerate dist/homebrew/jira-cli.rb for a given release tag.
# Idempotent: always rewrites from template, so re-running on any tag produces
# a clean formula regardless of the previous state.
#
# Usage: scripts/update-homebrew-formula.sh v0.1.0
set -eu

if [ $# -ne 1 ]; then
    echo "usage: $0 <version-tag>   (e.g. v0.1.0)" >&2
    exit 2
fi
TAG="$1"
VERSION="${TAG#v}"
REPO="${JIRA_CLI_REPO:-zhiyue/jira-cli}"
FORMULA="${JIRA_CLI_FORMULA:-dist/homebrew/jira-cli.rb}"

fetch_sha() {
    target="$1"
    url="https://github.com/${REPO}/releases/download/${TAG}/jira-cli-${TAG}-${target}.sha256"
    curl -fsSL "$url" | awk '{print $1}'
}

echo "==> Fetching sha256 for ${TAG}"
mac_arm="$(fetch_sha aarch64-apple-darwin)"
mac_x86="$(fetch_sha x86_64-apple-darwin)"
linux_arm="$(fetch_sha aarch64-unknown-linux-gnu)"
linux_x86="$(fetch_sha x86_64-unknown-linux-gnu)"

for v in "$mac_arm" "$mac_x86" "$linux_arm" "$linux_x86"; do
    if [ -z "$v" ] || [ "${#v}" -ne 64 ]; then
        echo "error: one of the sha256 values is missing or malformed" >&2
        exit 1
    fi
done

mkdir -p "$(dirname "$FORMULA")"

cat > "$FORMULA" <<EOF
# frozen_string_literal: true

# Auto-generated by scripts/update-homebrew-formula.sh — do not edit by hand.
# Regenerated on every release tag by .github/workflows/release.yml.

class JiraCli < Formula
  desc "Agent-first CLI for legacy Jira Server 8.13.5"
  homepage "https://github.com/${REPO}"
  license "Apache-2.0"
  version "${VERSION}"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/${REPO}/releases/download/${TAG}/jira-cli-${TAG}-aarch64-apple-darwin.tar.gz"
      sha256 "${mac_arm}"
    else
      url "https://github.com/${REPO}/releases/download/${TAG}/jira-cli-${TAG}-x86_64-apple-darwin.tar.gz"
      sha256 "${mac_x86}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/${REPO}/releases/download/${TAG}/jira-cli-${TAG}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_arm}"
    else
      url "https://github.com/${REPO}/releases/download/${TAG}/jira-cli-${TAG}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_x86}"
    end
  end

  def install
    bin.install "jira-cli"
  end

  test do
    assert_match "jira-cli", shell_output("#{bin}/jira-cli --version")
  end
end
EOF

echo "==> Wrote $FORMULA"
echo ""
echo "Summary:"
echo "  version:   $VERSION"
echo "  mac-arm:   $mac_arm"
echo "  mac-x86:   $mac_x86"
echo "  linux-arm: $linux_arm"
echo "  linux-x86: $linux_x86"
